services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    mem_limit: 250m

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    mem_limit: 96m

  kafka:
    image: apache/kafka:3.7.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_HEAP_OPTS: "-Xmx350m -Xms350m"
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
    mem_limit: 500m

  inventory-service:
    build: ./inventory-service
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      JDK_JAVA_OPTIONS: "-Xmx200m -Xss512k"
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    mem_limit: 300m

  payment-service:
    build: ./payment-service
    environment:
      DB_HOST: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JDK_JAVA_OPTIONS: "-Xmx200m -Xss512k"
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    mem_limit: 300m

  order-service:
    build: ./order-service
    environment:
      DB_HOST: postgres
      INVENTORY_SERVICE_URL: http://inventory-service:8081
      PAYMENT_SERVICE_URL: http://payment-service:8082
      JDK_JAVA_OPTIONS: "-Xmx200m -Xss512k"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      inventory-service:
        condition: service_started
      payment-service:
        condition: service_started
    mem_limit: 300m

  reconciliation-batch:
    build: ./reconciliation-batch
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      JDK_JAVA_OPTIONS: "-Xmx150m -Xss512k"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      inventory-service:
        condition: service_started
    mem_limit: 220m

volumes:
  pgdata:
  redisdata:
