server:
  port: 8081

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/inventory_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

logging:
  level:
    com.example.inventory: DEBUG
